import os

PHABRICATOR_URL = os.environ['PHABRICATOR_URL']
PHABRICATOR_URL_API = os.environ['PHABRICATOR_URL_API']
PHABRICATOR_TOKEN = os.environ['PHABRICATOR_TOKEN']
TELEGRAM_TOKEN = os.environ['TELEGRAM_TOKEN']
TELEGRAM_CHAT_NAME = os.environ['TELEGRAM_CHAT_NAME']
